### ISSUE TITLE
App crashes after notification permission is granted 

### ISSUE THREAD

**Issue by gabriel-munteanu** [X-SLAYER/notification_listener_service#11]
Hi!

I have an issues with this plugin. After I request permissions to listen to notifications and the user grants the permissions and then press back to return to the app, the app crashes with this exception
```
E/AndroidRuntime( 5500): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1199, result=0, data=null} to activity {com.gabrielmunteanu.banglejs_mobile/com.gabrielmunteanu.banglejs_mobile.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 5500): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5459)
E/AndroidRuntime( 5500): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5498)
E/AndroidRuntime( 5500): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
E/AndroidRuntime( 5500): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime( 5500): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 5500): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 5500): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2286)
E/AndroidRuntime( 5500): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 5500): 	at android.os.Looper.loopOnce(Looper.java:210)
E/AndroidRuntime( 5500): 	at android.os.Looper.loop(Looper.java:299)
E/AndroidRuntime( 5500): 	at android.app.ActivityThread.main(ActivityThread.java:8292)
E/AndroidRuntime( 5500): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5500): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/AndroidRuntime( 5500): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
E/AndroidRuntime( 5500): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 5500): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:432)
E/AndroidRuntime( 5500): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:266)
E/AndroidRuntime( 5500): 	at notification.listener.service.NotificationListenerServicePlugin.onActivityResult(NotificationListenerServicePlugin.java:129)
E/AndroidRuntime( 5500): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:807)
E/AndroidRuntime( 5500): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:430)
E/AndroidRuntime( 5500): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:811)
E/AndroidRuntime( 5500): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:719)
E/AndroidRuntime( 5500): 	at android.app.Activity.dispatchActivityResult(Activity.java:8633)
E/AndroidRuntime( 5500): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5452)
E/AndroidRuntime( 5500): 	... 13 more
```

Is strange that a few month ago when I started my app I didn't had this issue. Now I resumed development and I installed my dev environment on a new PC.
Flutter version: 3.3
Phone: Mi 10T Lite
Android: 12
MIUI: 13.0.12

**Comment by X-SLAYER** [comment]
Try the latest version of the plugin from the main branch
