### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference

### ISSUE THREAD

**Issue by shinewanna** [X-SLAYER/notification_listener_service#14]
Hello having this issue from your plugin, I got this from firebase crashlytics.

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
       at oc.c.<init>(:12)
       at oc.a.<init>(:48)
       at nc.e.b(:25)
       at notification.listener.service.NotificationListener.c(:18)
       at notification.listener.service.NotificationListener.onNotificationRemoved(:1)
       at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:432)
       at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:458)
       at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:471)
       at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2223)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8220)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)`

**Comment by X-SLAYER** [comment]
check latest update from the git main please
