### ISSUE TITLE
ClassCastException - VectorDrawable cannot be cast to BitmapDrawable

### ISSUE THREAD

**Issue by imdul** [X-SLAYER/notification_listener_service#24]
I don’t see this notification, I just get an error.

```
W/System.err(30401): java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
W/System.err(30401): 	at notification.listener.service.NotificationListener.getNotificationLargeIcon(NotificationListener.java:110)
W/System.err(30401): 	at notification.listener.service.NotificationListener.handleNotification(NotificationListener.java:54)
W/System.err(30401): 	at notification.listener.service.NotificationListener.onNotificationPosted(NotificationListener.java:36)
W/System.err(30401): 	at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:347)
W/System.err(30401): 	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2062)
W/System.err(30401): 	at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(30401): 	at android.os.Looper.loop(Looper.java:237)
W/System.err(30401): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
W/System.err(30401): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(30401): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
W/System.err(30401): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
D/ERROR LARGE ICON(30401): getNotificationLargeIcon: android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
```

**Comment by Juttu** [comment]
Hey, did you find a solution for this problem ?

**Comment by X-SLAYER** [comment]
what are the steps to reproduce please
